wip: refactored

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -10,8 +10,8 @@ on:
 
 env:
   PACKAGE_NAME: "com.pditta.githubactions.mytestlibrary"
-  VERSION_PREFIX: "25.03.0.19"
-  TAG_NAME: "25.03.0.19"
+  VERSION_PREFIX: "25.03.0.16"
+  TAG_NAME: ${{ env.TAG_NAME }}
 
 jobs:
   clean-package-registry:
@@ -29,20 +29,20 @@ jobs:
           # Ottieni tutte le versioni del pacchetto
           response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/user/packages/maven/$PACKAGE_NAME/versions")
-          
+
           echo "$response"
-          
+
           # Estrai l'ID della versione specifica (cerca per il nome della versione)
           version_id=$(echo "$response" | jq -r ".[] | select(.name == \"$VERSION_TO_DELETE\") | .id")
-          
+
           # Verifica se abbiamo trovato l'ID
           if [ -z "version_id" ]; then
             echo "La versione $VERSION_TO_DELETE esiste, procedo con la cancellazione."
-          
+
             delete_response=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE \
                                 -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                                 "https://api.github.com/user/packages/maven/$PACKAGE_NAME/versions/$version_id")
-          
+
             if [ "$delete_response" -eq 204 ]; then
               echo "La versione $VERSION_TO_DELETE è stata cancellata con successo."
             elif [ "$delete_response" -eq 404 ]; then
@@ -56,7 +56,7 @@ jobs:
             echo "La versione $VERSION_TO_DELETE non esiste, niente da cancellare."
           fi
 
-  remove-tag:
+  remove-tag-and-release:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout branch
@@ -65,16 +65,28 @@ jobs:
       - name: Set up Git
         uses: ./.github/actions/setup-git
 
-      - name: Check if Tag Exists
-        id: check_tag
-        run: |
-          if git ls-remote --tags origin | grep -q "refs/tags/${{ env.TAG_NAME }}"; then
-            echo "TAG_EXISTS=true" >> $GITHUB_OUTPUT
-          else
-            echo "TAG_EXISTS=false" >> $GITHUB_OUTPUT
-          fi
-
-      - name: Delete Git Tag
+      - name: Delete GitHub Release
         if: ${{ steps.check_tag.outputs.TAG_EXISTS == 'true' }}
         run: |
-          git push origin --delete ${{ env.TAG_NAME }}
+          release_id=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.TAG_NAME }}" | jq -r '.id')
+
+          echo "$release_id"
+
+          if [ "$release_id" != "null" ]; then
+            delete_response=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE \
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              "https://api.github.com/repos/${{ github.repository }}/releases/$release_id")
+
+            if [ "$delete_response" -eq 204 ]; then
+              echo "La release associata al tag ${{ env.TAG_NAME }} è stata cancellata con successo."
+            elif [ "$delete_response" -eq 404 ]; then
+              echo "Errore: La release associata al tag ${{ env.TAG_NAME }} non è stata trovata per la cancellazione."
+              exit 1
+            else
+              echo "Errore nella cancellazione della release. Codice di stato: $delete_response"
+              exit 1
+            fi
+          else
+            echo "Nessuna release associata al tag ${{ env.TAG_NAME }} trovata."
+          fi
